### ISSUE TITLE
Envie aqui

### ISSUE THREAD

**Issue by cavalcantigor** [cavalcantigor/eng-software-tdd#1]

**Comment by gpximenes** [comment]
https://github.com/gpximenes/Pytest

**Comment by Sawyo** [comment]
https://github.com/Sawyo/TDD---Engenharia-de-Software

**Comment by dominiquesalomao** [comment]
https://github.com/dominiquesalomao/AtividadeTDD

Integrantes: Dominique Salomão;
Ronald Frota e Jardielson.

**Comment by pgmagno** [comment]
https://github.com/pgmagno/tdd-activity

Equipe:
Paulo Magno
Paulo Marques
Yuri Ageme

**Comment by DredgenCipher** [comment]
[Repositório](https://github.com/DredgenCipher/AtividadeTDD)

[João Lucas](https://github.com/DredgenCipher)

**Comment by dcnascimento** [comment]
https://github.com/dcnascimento/engsoftTDD

Daniel C Nascimento
Jefferson Cordeiro

**Comment by maximoace** [comment]
[O repositório do github.](https://github.com/maximoace/eng-software-tdd)

Membros do Trio:

[Máximo Arthuro](https://github.com/maximoace)
[Luís Felipe](https://github.com/github.com/Luisfelipeqt)
[Laryssa Melonio](https://github.com/Larymelonio)

**Comment by euviniciuss** [comment]
Atividade TDD:
https://github.com/euviniciuss/tdd-atividade

Membros de equipe:
- Marcus Vinicius Silva Costa (https://github.com/euviniciuss)

Mais informações no README!

**Comment by AmandaCsouzaa** [comment]
https://github.com/AmandaCsouzaa/tdd-eng.soft/tree/main
Amanda Souza, Pedro Elizaldo e Matheus França

**Comment by avsmiih** [comment]
https://github.com/avsmiih/trabalho_tdd
Miriã Tavares Machado, e somente ela.

**Comment by cavalcantigor** [comment]
> https://github.com/gpximenes/Pytest

Diferença diagonal: Os testes como foram feitos não vão falhar nunca. Vocês testaram uma variável estática. Os testes precisam explorar casos em que pode falhar e necessariamente passar pela função a ser testada. A função de vocês performa em cima de uma matriz estática. Deveria receber como parâmetro.

Soma array: não foi testado nada de fato. Acredito que o código para resolver o problema ficou super complexo. É possível, da melhor maneira, resolver numa única linha de código (`sum(array)`).

Palindromo: Vocês rodaram os testes? A palavra "Daniel" não é palíndromo, mas o teste assegura que sim.

**Comment by cavalcantigor** [comment]
> https://github.com/Sawyo/TDD---Engenharia-de-Software

Os testes ficaram confusos, pois utilizou-se constantes declaradas dentro dos arquivos. Ou seja, todo teste usava exatamente o mesmo input. Cada teste tem a intenção de testar coisas diferentes, logo os inputs devem ser diferentes. De qualquer maneira, existem testes unitários, apesar de mal projetados.

**Comment by cavalcantigor** [comment]
> https://github.com/dominiquesalomao/AtividadeTDD
> 
> Integrantes: Dominique Salomão; Ronald Frota e Jardielson.

Não cumpriu com a proposta da atividade.

**Comment by cavalcantigor** [comment]
> https://github.com/pgmagno/tdd-activity
> 
> Equipe: Paulo Magno Paulo Marques Yuri Ageme

Parabéns pela atividade. Exatamente o que foi solicitado.

Uma dicazinha: evitar usar laços de repetição e desvios condicionais nos testes. De preferência, mantê-los simples (criar variáveis estáticas mesmo). Isso ajuda tanto no entendimento do teste, quanto no grau de confiança que se tem. Adicionando código no teste, pode provocar um teste viciado que oculta um bug (quem testa o teste?).

Parabéns :)

**Comment by cavalcantigor** [comment]
> [Repositório](https://github.com/DredgenCipher/AtividadeTDD)
> 
> [João Lucas](https://github.com/DredgenCipher)

Parabéns pela atividade :)

**Comment by cavalcantigor** [comment]
> https://github.com/dcnascimento/engsoftTDD
> 
> Daniel C Nascimento Jefferson Cordeiro

Gostei muito de como usou o JUnit, explorando os recurso de mock e beforeEach. Excelente trabalho. Parabéns :)

**Comment by cavalcantigor** [comment]
> [O repositório do github.](https://github.com/maximoace/eng-software-tdd)
> 
> Membros do Trio:
> 
> [Máximo Arthuro](https://github.com/maximoace) [Luís Felipe](https://github.com/github.com/Luisfelipeqt) [Laryssa Melonio](https://github.com/Larymelonio)

Simples, objetivo e correto. :)

**Comment by cavalcantigor** [comment]
> Atividade TDD: https://github.com/euviniciuss/tdd-atividade
> 
> Membros de equipe:
> 
> * Marcus Vinicius Silva Costa (https://github.com/euviniciuss)
> 
> Mais informações no README!

Gostei do zelo nos arquivos .MD :) de muito bom gosto.
Mostrou que conhece a linguagem que usou para atividade, explorando os recursos dela. Código limpo, fácil de entender, bem como os testes. Parabéns :)

**Comment by cavalcantigor** [comment]
> https://github.com/AmandaCsouzaa/tdd-eng.soft/tree/main Amanda Souza, Pedro Elizaldo e Matheus França

Não cumpriu com a proposta da atividade.

**Comment by cavalcantigor** [comment]
> https://github.com/avsmiih/trabalho_tdd Miriã Tavares Machado, e somente ela.

Mesmo problema do Sawyo: os testes ficaram confusos, pois utilizou-se constantes declaradas dentro dos arquivos. A diferença é que não havia exatamente testes unitários.
Entrega após o horário.
Apesar disso, foi a única a reportar a dificuldade e entrar em contato. Esforço também é premiado :)
